# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--lines-after-imports=2, --force-single-line-imports, --line-length=120, --force-alphabetical-sort-within-sections, --profile=black]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.11
      args: [--line-length=120]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.10.0]
- repo: https://github.com/hadialqattan/pycln
  rev: v2.1.1
  hooks:
    - id: pycln
      language_version: python3.11
      args: [--all]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        language_version: python3.11
        args: [--ignore-missing-imports, --namespace-packages, --explicit-package-bases]
        additional_dependencies: [
          types-setuptools==65.4.0.0,
          types-python-dateutil==2.8.19,
          types-requests==2.28.11.2,
          types-urllib3==1.26.25.1,
          'types-aiobotocore[essential]==2.4.2',
        ]
